assets/AssetsInventory/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetsInventory.DTO;
using AssetsInventory.Models;
using AssetsInventory.ViewModels;

namespace AssetsInventory.Controllers
{

    public class CategoryController : BaseAdminController
    {
        private AssetContext db = new AssetContext();

        //
        // GET: /Category/

        public ViewResult Index()
        {
            return View(db.Categories.ToList());
        }

        public JsonResult List()
        {
            var data = db.Categories.ToList().Select(x => new CategoryDTO
                                                              {
                                                                  CategoryId = x.CategoryId,
                                                                  CategoryName = x.CategoryName,
                                                                  Prefix = x.Prefix 
                                                              });
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Category/Details/5

        public ViewResult Details(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        //
        // GET: /Category/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Category/Create

        [HttpPost]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(category);
        }
        
        //
        // GET: /Category/Edit/5
 
        public ActionResult Edit(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        //
        // POST: /Category/Edit/5

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //
        // GET: /Category/Delete/5
 
        public ActionResult Delete(int id)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }

        //
        // POST: /Category/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult CategoryDropdown(int? categoryid)
        {
            var data = db.Categories.ToList().Select(x=> new CategoryDTO
                                                             {
                                                                 CategoryId = x.CategoryId,
                                                                 CategoryName = x.CategoryName + " - " + x.CategoryId
                                                             });
            ViewBag.CategoryId = new SelectList(data.OrderBy(x=>x.CategoryName), "CategoryId", "CategoryName",categoryid.HasValue ? categoryid.ToString() : string.Empty);
            var model = new CategoryDropdownViewModel();
            return PartialView("CategoryDropdown", model);
        }
    }
}

assets/AssetsInventory/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetsInventory.Models;

namespace AssetsInventory.Controllers
{ 
    public class DocumentController : BaseAdminController
    {
        private AssetContext db = new AssetContext();


        #region Auto-Generated

        //
        // GET: /Document/

        public ViewResult Index()
        {
            var documents = db.Documents.Include(d => d.Asset);
            return View(documents.ToList());
        }

        //
        // GET: /Document/Details/5

        public ViewResult Details(int id)
        {
            Document document = db.Documents.Find(id);
            return View(document);
        }

        //
        // GET: /Document/Create

        public ActionResult Create()
        {
            ViewBag.AssetId = new SelectList(db.Assets, "AssetId", "AssetUniqueId");
            return View();
        } 

        //
        // POST: /Document/Create

        [HttpPost]
        public ActionResult Create(Document document)
        {
            if (ModelState.IsValid)
            {
                db.Documents.Add(document);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.AssetId = new SelectList(db.Assets, "AssetId", "AssetUniqueId", document.AssetId);
            return View(document);
        }
        
        //
        // GET: /Document/Edit/5
 
        public ActionResult Edit(int id)
        {
            Document document = db.Documents.Find(id);
            ViewBag.DocumentTypeId = new SelectList(db.DocumentTypes, "DocumentTypeId", "DocumentTypeName",document.DocumentTypeId);
            return View(document);
        }

        //
        // POST: /Document/Edit/5

        [HttpPost]
        public ActionResult Edit(Document document)
        {
            if (ModelState.IsValid)
            {
                db.Entry(document).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit", "Asset", new { id = document.AssetId });  
            }
            ViewBag.DocumentTypeId = new SelectList(db.DocumentTypes, "DocumentTypeId", "DocumentTypeName", document.DocumentTypeId);
            return View(document);
        }

        //
        // GET: /Document/Delete/5
 
        public ActionResult Delete(int id)
        {
            Document document = db.Documents.Find(id);
            return View(document);
        }

        //
        // POST: /Document/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Document document = db.Documents.Find(id);
            var assetid = document.AssetId;
            db.Documents.Remove(document);
            db.SaveChanges();
            return RedirectToAction("Edit", "Asset", new { id = assetid });  
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        #endregion

        public ActionResult AssetCreate(int id)
        {
            var model = new Document {AssetId = id};
            ViewBag.DocumentTypeId = new SelectList(db.DocumentTypes, "DocumentTypeId", "DocumentTypeName");
            return View(model);
        }


        [HttpPost]
        public ActionResult AssetCreate(int id, Document document, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/asset-data"), fileName);
                    file.SaveAs(path);

                    document.DocumentName = fileName;
                    
                    db.Documents.Add(document);
                    db.SaveChanges();
                    return RedirectToAction("Edit", "Asset", new { id = document.AssetId });
                }
               
            }
            

            return RedirectToAction("Edit", "Asset", new {id = id});
        }

        public void DownloadFile(int id)
        {
            var document = db.Documents.Find(id);
            if (!String.IsNullOrEmpty(document.DocumentName))
            {
                HttpContext.Response.AddHeader("content-disposition", "attachment; filename=" + document.DocumentName);
            }
            
            var filePath = HttpContext.Server.MapPath("/Content/asset-data/" + document.DocumentName);
                HttpContext.Response.TransmitFile(filePath);
        }

    }
}

assets/AssetsInventory/Controllers/LocationController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using AssetsInventory.DTO;
using AssetsInventory.Models;
using AssetsInventory.ViewModels;

namespace AssetsInventory.Controllers
{ 
    public class LocationController : BaseAdminController
    {
        private readonly AssetContext db = new AssetContext();

        //
        // GET: /Location/

        public ViewResult Index()
        {
            return View(db.Locations.ToList());
        }

        //
        // GET: /Location/Details/5

        public ViewResult Details(int id)
        {
            Location location = db.Locations.Find(id);
            return View(location);
        }

        //
        // GET: /Location/Create
        protected override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            //handle error for delete referential
            //if (filterContext.RouteData.Values["action"].ToString() == "Delete")
            //{
            //    filterContext.ExceptionHandled = true;

            //    var returnurl = filterContext.HttpContext.Request.RawUrl;
            //    //TempData["ErrorMsg"] = filterContext.Exception.InnerException.InnerException.Message;
            //    TempData["ErrorMsg"] = "Cannot Delete this Record Since It is being referenced by another Record";
            //    TempData["DeleteUrl"] = returnurl;
            //    //RedirectToAction("DeleteHandler");
            //    filterContext.Result = View("DeleteHandler");
            //}
            if (filterContext.RouteData.Values["action"].ToString() == "Edit" ||
                filterContext.RouteData.Values["action"].ToString() == "Create")
            {
                filterContext.ExceptionHandled = true;

                var returnurl = filterContext.HttpContext.Request.RawUrl;
                //TempData["ErrorMsg"] = filterContext.Exception.InnerException.InnerException.Message;
                TempData["ErrorMsg"] = "Cannot Update this Record. Location ID aready exists";
                TempData["DeleteUrl"] = returnurl;
                //RedirectToAction("DeleteHandler");
                filterContext.Result = Redirect(returnurl);
            }
        }

        public ActionResult Create()
        {
            ViewBag.CountryId = new SelectList(db.Countries.OrderBy(x => x.SortCode).ThenBy(x => x.CountryName).Where(x=>x.IsShown), "CountryId", "CountryName", 1);
            return View();
        } 

        //
        // POST: /Location/Create

        [HttpPost]
        public ActionResult Create(Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }
            ViewBag.CountryId = new SelectList(db.Countries.OrderBy(x=>x.SortCode).ThenBy(x=>x.CountryName).Where(x=>x.IsShown), "CountryId", "CountryName", location.CountryId);
            return View(location);
        }
        
        //
        // GET: /Location/Edit/5
 
        public ActionResult Edit(int id)
        {
            var location = db.Locations.Find(id);
            ViewBag.CountryId = new SelectList(db.Countries.OrderBy(x=>x.SortCode).ThenBy(x=>x.CountryName).Where(x=>x.IsShown), "CountryId", "CountryName", location.CountryId);
            return View(location);
        }

        //
        // POST: /Location/Edit/5

        [HttpPost]
        public ActionResult Edit(Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CountryId = new SelectList(db.Countries.OrderBy(x=>x.SortCode).ThenBy(x=>x.CountryName).Where(x=>x.IsShown), "CountryId", "CountryName", location.CountryId);
            return View(location);
        }

        //
        // GET: /Location/Delete/5
 
        public ActionResult Delete(int id)
        {
            Location location = db.Locations.Find(id);
            return View(location);
        }

        //
        // POST: /Location/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult LocationDropdown(int? id,int? countryid,string controlname)
        {
            IList<LocationDTO> locations;
            if (!countryid.HasValue)
            {
                locations = db.Locations.ToList().Select(x => new LocationDTO
                                                             {
                                                                 Id = x.LocationId,
                                                                 Name = x.LocationName + " - " + x.CostCenterCode
                                                             }).ToList();
            }
            else
            {
                locations = db.Locations.Where(x=>x.CountryId == countryid).ToList().Select(x => new LocationDTO
                {
                    Id = x.LocationId,
                    Name = x.LocationName + " - " + x.CostCenterCode
                }).ToList();
            }
            var defaultvalue = locations.FirstOrDefault();
           // ViewBag.LocationID = new SelectList(locations, "Id", "Name",id.HasValue ? id.ToString() : defaultvalue != null ? defaultvalue.Id.ToString() : string.Empty);
            var model = new LocationDropdownViewModel(controlname);
            model.CountryId = countryid;
            model.SelectedId = id;
            return PartialView("LocationDropdown", model);
        }


        public JsonResult LocationDropdownList(int? id, int? countryid)
        {
            IList<LocationDTO> locations;
            if (!countryid.HasValue)
            {
                locations = db.Locations.ToList().Select(x => new LocationDTO
                {
                    Id = x.LocationId,
                    Name = x.LocationName + " - " + x.CostCenterCode
                }).ToList();
            }
            else
            {
                locations = db.Locations.Where(x => x.CountryId == countryid).ToList().Select(x => new LocationDTO
                {
                    Id = x.LocationId,
                    Name = x.LocationName + " - " + x.CostCenterCode
                }).ToList();
            }
            var defaultvalue = locations.FirstOrDefault();
            return
                Json(
                    new SelectList(locations, "Id", "Name",
                                   id.HasValue
                                       ? id.ToString()
                                       : defaultvalue != null ? defaultvalue.Id.ToString() : string.Empty),
                    JsonRequestBehavior.AllowGet);

        }

        public ActionResult CreateDialog()
        {
            return PartialView("CreateDialog");
        }

        [HttpPost]
        public ActionResult CreateDialog(Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                
            }
            return LocationDropdown(null,null,string.Empty);
            
        }
    }
}

assets/AssetsInventory/Views/Asset/AssetInfo.cshtml
@model AssetsInventory.Models.Asset

<div id="create-dialog"></div>           
<fieldset>
        <legend>Asset</legend>

        @if (Model != null)
        {
        <div class="editor-label">
            @Html.LabelFor(model => model.AssetUniqueId, @AssetResource.AssetResource.AssetUniqueid)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.AssetUniqueId, new { @readonly = "readonly" })
        </div>
        }
        
 
        <div class="editor-field">
            @Html.CheckBoxFor(model => model.IsPart) @Html.LabelFor(model => model.IsPart, @AssetResource.AssetResource.IfPartLabel)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId, @AssetResource.AssetResource.Category)
        </div>
        <div class="editor-field">
        <span id="categorydiv"></span>
        @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubCategoryId, @AssetResource.AssetResource.SubCategory)
        </div>
        <div class="editor-field">
        <span id="subcategorydiv"></span>
        @Html.ValidationMessageFor(model => model.SubCategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description, @AssetResource.AssetResource.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description, new { @class = "comment" })
        </div>

        <div class="editor-label" >
            @Html.LabelFor(model => model.ManufacturerId, @AssetResource.AssetResource.Manufacturer)
        </div>
        <div class="editor-field" >
        <span id="manufacturerdiv"></span>
        @Html.ValidationMessageFor(model => model.ManufacturerId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ModelTypeID, @AssetResource.AssetResource.ModelType)
        </div>
        <div class="editor-field">
            <span id="modeltypediv"></span>
        @Html.ValidationMessageFor(model => model.ModelTypeID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SerialNumber, @AssetResource.AssetResource.SerialNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SerialNumber)
            @Html.ValidationMessageFor(model => model.SerialNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ArrangementNumber, @AssetResource.AssetResource.ArrangementNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ArrangementNumber)
            @Html.ValidationMessageFor(model => model.ArrangementNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LocationID, @AssetResource.AssetResource.Location)
        </div>
        <div class="editor-field">
            <span id="locationdiv"></span>
         @Html.ValidationMessageFor(model => model.LocationID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AssetPurchasePrice, @AssetResource.AssetResource.PurchasePrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AssetPurchasePrice)
            @Html.ValidationMessageFor(model => model.AssetPurchasePrice)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FairMarketPrice, @AssetResource.AssetResource.FairMarketPrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FairMarketPrice)
            @Html.ValidationMessageFor(model => model.FairMarketPrice)
        </div>

       @* <div class="editor-label">
            @Html.LabelFor(model => model.MaterialTransferNumber, @AssetResource.AssetResource.MaterialTransferNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaterialTransferNumber)
            @Html.ValidationMessageFor(model => model.MaterialTransferNumber)
        </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.ConditionEvaluationID, @AssetResource.AssetResource.ConditionEvaluation)
        </div>
        <div class="editor-field" id="conditiondiv">
         
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comment, @AssetResource.AssetResource.Comment)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Comment, new { @class = "comment" })
            @Html.ValidationMessageFor(model => model.Comment)
        </div>
  

        @*<p>
            @if (Model != null)
            {
            <input type="submit" value="@AssetResource.Common.Submit" />
            }
            else
            { 
            <input type="submit" value="@AssetResource.Common.Create" class="save-btn"/>
            }
        </p>*@
    </fieldset>
    

<script type="text/javascript">
    $(document).ready(function () {
       // $(".lookup").button({ icons: { primary: "ui-icon-newwin"} });
        $(".lookup").hide();
        loadCategory();

        //loadManufacturer();

        loadLocation();

        loadCondition();

        //$( "#create-dialog" ).dialog( "destroy" );
//        $( "#create-dialog" ).dialog({
//			autoOpen: false
//		});

        


    });

    function loadCategory() {
        @if (Model != null && Model.CategoryId.HasValue)
        {
            <text>
            var url = '@(Url.Action("CategoryDropdown", "Category", new { categoryid = Model.CategoryId }))';
            </text>
        }
        else
        {
            <text>
            var url = '@(Url.Action("CategoryDropdown", "Category"))';
            </text>
        }
        
        $("#categorydiv").load(url);
    }

    function loadManufacturer() {
        var id = $("#CategoryId").val();
        var catid = id.length == 0 ? 0 : parseInt(id);
        @if (Model != null && Model.ManufacturerId.HasValue)
        {
            <text>
            var url = '@(Url.Action("AssetManufacturerDropdown", "Manufacturer", new { id = Model.ManufacturerId }))';
            </text>
        }
        else
        {
            <text>
            var url = '@(Url.Action("AssetManufacturerDropdown", "Manufacturer"))';
            </text>
        }
        var loadurl = url + '?catid=' + catid.toString();

        $("#manufacturerdiv").load(loadurl);
    }

    function loadSubcategory() {
        var url = '@(Url.Action("SubCategoryDropdown", "SubCategory"))';
        var id = $("#CategoryId").val();
        var catid = id.length == 0 ? 0 : parseInt(id);
        @if (Model != null && Model.SubCategoryId.HasValue)
        {
            <text>
            var loadurl = url + "/" + catid + "?subcatid=@(Model.SubCategoryId)";
            </text>
        }
        else
        {
            <text>
            var loadurl = url + "/" + catid;
            
            </text>
        }
        
       
        
        $("#subcategorydiv").load(loadurl);
    }

    function loadModelType() {

        
        var url = '@(Url.Action("ModelTypeDropdown", "ModelType"))';
        var id = $("#ManufacturerId").val();
        var manufacturerid = id.length == 0 ? 0 : parseInt(id);
        var loadurl = url + "/" + manufacturerid;

        @if (Model != null && Model.ModelTypeID.HasValue)
        {
            <text>
            var loadurl = url + "/" + manufacturerid + "?modeltypeid=@(Model.ModelTypeID)";
            </text>
        }
        else
        {
            <text>
            var loadurl = url + "/" + manufacturerid;
            
            </text>
        }

        $("#modeltypediv").load(loadurl);
    }

    function loadLocation() {
        @if (Model != null && Model.LocationID.HasValue)
        {
            <text>
            var url = '@(Url.Action("LocationDropdown", "Location", new { id = Model.LocationID }))';
            </text>
        }
        else
        {
            <text>
            var url = '@(Url.Action("LocationDropdown", "Location"))';
            </text>
        }
        
        $("#locationdiv").load(url);
    }


    function loadCondition() {
        @if (Model != null && Model.ConditionEvaluationID.HasValue)
        {
            <text>
            var url = '@(Url.Action("ConditionEvaluationDropdown", "ConditionEvaluation", new { id = Model.ConditionEvaluationID }))';
            </text>
        }
        else
        {
            <text>
           var url = '@(Url.Action("ConditionEvaluationDropdown", "ConditionEvaluation"))';
            </text>
        }
        
        $("#conditiondiv").load(url);
    }

    function getSubcategoryTemplate(){
        var url = '@(Url.Action("GetTemplate", "SubCategory"))';
        var subcat = $("#SubCategoryId").val()
        var txtdescription = $("#Description");
        
        $.getJSON(url + "/" + subcat, function(data) {
            txtdescription.val(data);
        });
    }

</script>

assets/AssetsInventory/Views/Asset/Create.cshtml
@model AssetsInventory.Models.Asset

@{
    ViewBag.Title = @AssetResource.AssetResource.AssetIndexTitle;
}

<h2>@AssetResource.AssetResource.AssetIndexTitle</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(false,"Please fix the following errors") @Html.Partial("ErrorMsg")
    @Html.Partial("AssetInfo",Model)

    <div>
        <input type="submit" value="@AssetResource.Common.Create" class="save-btn" />
        @Html.ActionLink(@AssetResource.Common.BacktoList, "Index", null, new { @class="redirect-lnk"})
    </div>
}

assets/AssetsInventory/Views/Asset/Edit.cshtml
@model AssetsInventory.Models.Asset

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(false,"Please fix the following errors") @Html.Partial("ErrorMsg")
    @Html.HiddenFor(model => model.AssetId)
    @Html.Partial("AssetInfo", Model)

    <div>
        <fieldset>
            <legend>Additional Information</legend>
            @Html.ActionLink("Shipping Info", "AddShippingInfo", new { id = Model.AssetId })<br />
            @Html.ActionLink("Purchase Info", "AddPurchaseInfo", new { id = Model.AssetId })
        </fieldset>
    </div>
    

    
    <!-- documents -->
    <div>
        <fieldset>
             @Html.ActionLink("Add Documents", "AssetCreate", "Document", new { id = Model.AssetId }, null)<br />
            <legend>Documents</legend>
                <table>
                <tr>
                <th>
                DocumentName
                </th>
                <th>
                DocumentDescription
                </th>
                <th></th>
                </tr>

                @foreach (var item in Model.Documents)
                {
                <tr>
                <td>
                @Html.ActionLink(item.DocumentName,"DownloadFile","Document",new { id = item.DocumentId},null)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.DocumentDescription)
                </td>
               
                <td>
                @Html.ActionLink(@AssetResource.Common.Edit, "Edit", "Document", new { id = item.DocumentId }, null) |
                @Html.ActionLink(@AssetResource.Common.Delete, "Delete","Document", new { id = item.DocumentId },null)
                </td>
                </tr>
                }

                </table>
        </fieldset>
    </div>
    
    <!-- photos -->
    <div>
        <fieldset>
             @Html.ActionLink("Add Photo", "AssetCreate", "PhotoArchive", new { id = Model.AssetId }, null)<br />
            <legend>Photo Archive</legend>
                <table>
                <tr>
                <th>
                Filename
                </th>
                <th>
                DateUploaded
                </th>
                <th></th>
                </tr>

                @foreach (var item in Model.PhotoArchives)
                {
                <tr>
                <td>
                @Html.ActionLink(item.PhotoFileName, "DownloadFile", "PhotoArchive", new { id = item.PhotoArchiveId }, null)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.DateUploaded)
                </td>
               
                <td>
                @Html.ActionLink(@AssetResource.Common.Edit, "Edit","PhotoArchive", new { id = item.PhotoArchiveId },null)
                </td>
                </tr>
                }

                </table>
        </fieldset>
    </div>
    
    
    
    <div>
        <input type="submit" value="@AssetResource.Common.Submit" />
    </div>
  
}
<div>
    @Html.ActionLink(@AssetResource.Common.BacktoList, "Index", null, new { @class = "redirect-lnk" })
</div>