assets/AssetsInventory/ViewModels/SubCategoryDropdownViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AssetsInventory.ViewModels
{
    public class SubCategoryDropdownViewModel
    {
        public int? SubCategoryId { get; set; }
    }
}

assets/AssetsInventory/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetsInventory.DTO;
using AssetsInventory.Models;
using AssetsInventory.ViewModels;

namespace AssetsInventory.Controllers
{ 
    public class SubCategoryController : BaseAdminController
    {
        private AssetContext db = new AssetContext();

        //
        // GET: /SubCategory/

        public ViewResult Index()
        {
            var subcategories = db.SubCategories.Include(s => s.Category);
            return View(subcategories.ToList());
        }

        public JsonResult List()
        {
            var data = db.SubCategories.Include(s => s.Category).ToList().Select(x => new SubCategoryDTO
                                                                                          {
                                                                                              CategoryName =
                                                                                                  x.Category.
                                                                                                  CategoryName,
                                                                                              SubCategoryId =
                                                                                                  x.SubCategoryId,
                                                                                              SubCategoryName =
                                                                                                  x.SubCategoryName
                                                                                          });
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /SubCategory/Details/5

        public ViewResult Details(int id)
        {
            SubCategory subcategory = db.SubCategories.Find(id);
            return View(subcategory);
        }

        //
        // GET: /SubCategory/Create

        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x=>x.CategoryName), "CategoryId", "CategoryName");
            return View();
        } 

        //
        // POST: /SubCategory/Create

        [HttpPost]
        public ActionResult Create(SubCategory subcategory)
        {
            if (ModelState.IsValid)
            {
                db.SubCategories.Add(subcategory);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x => x.CategoryName), "CategoryId", "CategoryName", subcategory.CategoryId);
            return View(subcategory);
        }
        
        //
        // GET: /SubCategory/Edit/5
 
        public ActionResult Edit(int id)
        {
            SubCategory subcategory = db.SubCategories.Find(id);
            ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x => x.CategoryName), "CategoryId", "CategoryName", subcategory.CategoryId);
            return View(subcategory);
        }

        //
        // POST: /SubCategory/Edit/5

        [HttpPost]
        public ActionResult Edit(SubCategory subcategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subcategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x => x.CategoryName), "CategoryId", "CategoryName", subcategory.CategoryId);
            return View(subcategory);
        }

        //
        // GET: /SubCategory/Delete/5
 
        public ActionResult Delete(int id)
        {
            SubCategory subcategory = db.SubCategories.Find(id);
            return View(subcategory);
        }

        //
        // POST: /SubCategory/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            SubCategory subcategory = db.SubCategories.Find(id);
            db.SubCategories.Remove(subcategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        public ActionResult AddSubCategory(int id)
        {
            ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x => x.CategoryName), "CategoryId", "CategoryName", id);
            return View();
        }

        [HttpPost]
        public ActionResult AddSubCategory(SubCategory subcategory)
        {
            if (ModelState.IsValid)
            {
                db.SubCategories.Add(subcategory);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return RedirectToAction("AddSubCategory", new {id = subcategory.CategoryId});
            }

            ViewBag.CategoryId = new SelectList(db.Categories.OrderBy(x => x.CategoryName), "CategoryId", "CategoryName", subcategory.CategoryId);
            return View(subcategory);
        }

        /// <summary>
        /// partial view for ajax sub category dropdown
        /// </summary>
        /// <param name="id">category id</param>
        /// <param name="subcatid">sub category id</param>
        /// <returns></returns>
        public ActionResult SubCategoryDropdown(int id,int? subcatid)
        {
            var data = db.SubCategories.Where(x => x.CategoryId == id);
            ViewBag.SubCategoryId = new SelectList(data, "SubCategoryId", "SubCategoryName",subcatid.HasValue ? subcatid.ToString() : string.Empty);
            var model = new SubCategoryDropdownViewModel();
            return PartialView("SubCategoryDropdown",model);
        }

        public JsonResult GetTemplate(int id)
        {
            var data = db.SubCategories.Find(id);
            return Json(data.DescriptionTemplate, JsonRequestBehavior.AllowGet);
        }

    }
}

assets/AssetsInventory/Views/SubCategory/AddSubCategory.cshtml
@model AssetsInventory.Models.SubCategory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(false,"Please fix the following errors") @Html.Partial("ErrorMsg")
    <fieldset>
        <legend>SubCategory</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId, "Category")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryId", String.Empty)
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubCategoryName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SubCategoryName)
            @Html.ValidationMessageFor(model => model.SubCategoryName)
        </div>

        <p>
            <input type="submit" value="@AssetResource.Common.Create" class="save-btn"/>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink(@AssetResource.Common.BacktoList, "Index","Category")
</div>

assets/AssetsInventory/Views/SubCategory/Create.cshtml
@model AssetsInventory.Models.SubCategory

@{
    ViewBag.Title = @AssetResource.AssetResource.SubCategory;
}

<h2>@AssetResource.AssetResource.SubCategory</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(false,"Please fix the following errors") @Html.Partial("ErrorMsg")
    <fieldset>
        <legend>SubCategory</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId, "Category")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryId", null, new { @style = "width:400px" })
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubCategoryName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SubCategoryName)
            @Html.ValidationMessageFor(model => model.SubCategoryName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MarkinginInstructions)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.MarkinginInstructions)
            @Html.ValidationMessageFor(model => model.MarkinginInstructions)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CertOrDocRequirement)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.CertOrDocRequirement)
            @Html.ValidationMessageFor(model => model.CertOrDocRequirement)
        </div>
        
    </fieldset>
    <p>
            <input type="submit" value="@AssetResource.Common.Create" class="save-btn"/>
            @Html.ActionLink(@AssetResource.Common.BacktoList, "Index", null, new { @class = "redirect-lnk" })
        </p>
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#CategoryId").kendoDropDownList();

    });
</script>

assets/AssetsInventory/Views/SubCategory/Delete.cshtml
@model AssetsInventory.Models.SubCategory

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>SubCategory</legend>

    <div class="display-label">Category</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category.CategoryName)
    </div>

    <div class="display-label">SubCategoryName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SubCategoryName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" class="save-btn"/> |
        @Html.ActionLink(@AssetResource.Common.BacktoList, "Index", null, new { @class = "redirect-lnk" })
    </p>
}

assets/AssetsInventory/Views/SubCategory/Details.cshtml
@model AssetsInventory.Models.SubCategory

@{
    ViewBag.Title = "Details";
}

<h2>@AssetResource.Common.Details</h2>

<fieldset>
    <legend>SubCategory</legend>

    <div class="display-label">Category</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category.CategoryName)
    </div>

    <div class="display-label">SubCategoryName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SubCategoryName)
    </div>
    @{Html.RenderPartial("SystemValues", new AssetsInventory.ViewModels.SystemDisplayPageViewModel(Model));}
</fieldset>
<p>
    @Html.ActionLink(@AssetResource.Common.Edit, "Edit", new { id = Model.SubCategoryId }, new { @class="edit-lnk"}) |
    @Html.ActionLink(@AssetResource.Common.BacktoList, "Index", null, new { @class = "redirect-lnk" })
</p>

assets/AssetsInventory/Views/SubCategory/Edit.cshtml
@model AssetsInventory.Models.SubCategory

@{
    ViewBag.Title = @AssetResource.AssetResource.SubCategory;
}

<h2>@AssetResource.AssetResource.SubCategory</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(false,"Please fix the following errors") @Html.Partial("ErrorMsg")
    <fieldset>
        <legend>SubCategory</legend>

        @Html.HiddenFor(model => model.SubCategoryId)

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId, "Category")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryId", null, new { @style = "width:400px" })
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubCategoryName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SubCategoryName)
            @Html.ValidationMessageFor(model => model.SubCategoryName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.MarkinginInstructions)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.MarkinginInstructions)
            @Html.ValidationMessageFor(model => model.MarkinginInstructions)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CertOrDocRequirement)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.CertOrDocRequirement)
            @Html.ValidationMessageFor(model => model.CertOrDocRequirement)
        </div>
        
    </fieldset>
    <p>
            <input type="submit" value="Save" class="save-btn"/>
             @Html.ActionLink(@AssetResource.Common.BacktoList, "Index", null, new { @class = "redirect-lnk" })
        </p>
    @Html.Partial("CreatedValues")
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#CategoryId").kendoDropDownList();

    });
</script>

assets/AssetsInventory/Views/SubCategory/Index.cshtml
@model IEnumerable<AssetsInventory.Models.SubCategory>

@{
    ViewBag.Title = @AssetResource.AssetResource.SubCategory;
}

<h2>@AssetResource.AssetResource.SubCategory</h2>

<p>
    @Html.ActionLink(@AssetResource.Common.CreateNew, "Create", null, new { @class = "create-btn" })
</p>
@Html.Partial("GridPageCounter") <div id="grid"></div>

<script id="gridtemplate" type="text/x-kendo-template">
    <a href='@(Url.Action("Edit"))/#= SubCategoryId #'>@AssetResource.Common.Edit</a> |
    <a href='@(Url.Action("Details"))/#= SubCategoryId #'>@AssetResource.Common.Details</a> |
    <a href='@(Url.Action("Delete"))/#= SubCategoryId #'>@AssetResource.Common.Delete</a>
</script>

<script type="text/javascript">
    $(document).ready(function () {
        var sharableDataSource = new kendo.data.DataSource({
            transport: {
                read: {
                    url: '@(Url.Action("List", "SubCategory"))',
                    dataType: "json"
                }
            },
            pageSize: @(ViewData["pagesize"]),
            schema: {
                data: function (result) {
                    return result;
                },
                total: function (result) {
                    return result.length;
                }
            },
            change: function () {
                var info = $(".k-grid-pager .info");

                // if it does not exist yet - create it
                if (!info.length) {
                    info = $('<div class="info"/>').appendTo(".k-grid-pager");
                }

                // set the text of the "info" div
                info.text(kendo.format("@(AssetResource.Common.PageDisplay) {0} - {1} of {2}",
                              (this.page() - 1) * this.pageSize() + 1, //first item in the page
                               Math.min(this.page() * this.pageSize(), this.total()), // last item in the page
                               this.total() // all items
                 ));
            }
        });

        $(document).ready(function () {



            $("#grid").kendoGrid({
                dataSource: sharableDataSource,
                height: 470,
                filterable: true,
                sortable: true,
                pageable: true,
                columns: [

                        {
                            field: "CategoryName",
                            title: "CategoryName"
                        },
                        {
                            field: "SubCategoryName",
                            title: "SubCategoryName"
                        },
                         {
                             field: "SubCategoryId",
                             title: " ",
                             template: kendo.template($("#gridtemplate").html()),
                             filterable: false,
                             sortable: false
                         }

                        ]
            });




        });

    });
</script>

assets/AssetsInventory/Views/SubCategory/SubCategoryDropdown.cshtml
@model AssetsInventory.ViewModels.SubCategoryDropdownViewModel 

@Html.DropDownList("SubCategoryId", null, new { @style = "width:400px;" }) <a href="javascript:void(0)" id="subcategorylookup" class="lookup">&nbsp;</a>
@Html.ValidationMessageFor(model => model.SubCategoryId)

<script type="text/javascript">
    $(document).ready(function () {
        

        $(".lookup").button({ icons: { primary: "ui-icon-newwin"} });
        $(".lookup").hide();
        $("#SubCategoryId").kendoDropDownList();
//        var ddSubCategory = $("#SubCategoryId").data("kendoDropDownList");
//        ddSubCategory.ul.width(400);
        $("#SubCategoryId").change(function () {
            getSubcategoryTemplate();
        });

        
        
        
    });
</script>